### ISSUE TITLE
`Go get` fails

### ISSUE THREAD

**Issue by pinpox** [derricw/siggo#18]
Hello,

I just wanted to install `siggo` but the go get command fails:

```bash
go get github.com/derricw/siggo
# github.com/derricw/siggo/cmd
.go/src/github.com/derricw/siggo/cmd/cfg.go:83:13: constant -1 overflows tcell.Color
```

**Comment by derricw** [comment]
yo! Thanks @pinpox for the report. I never even considered installing like that. I'll take a look. If you want to get going in the meantime, you should be able to build by cloning and running `make build`.

**Comment by derricw** [comment]
Ok, I'm able to reproduce your error. Hopefully I'll have a fix for you soon.

**Comment by derricw** [comment]
It seems like this really boils down to `go get` building siggo with a different version of tview than what is specified in the go.mod file. I'm not sure if there is a way to get it to use the dependency versions in siggo's go.mod file. Do you know of a way?

**Comment by derricw** [comment]
Looks like if you: `export GO111MODULE=on` it will build using the correct dependency versions.
