### ISSUE TITLE
Exit status 1 when trying to send messages in signal

### ISSUE THREAD

**Issue by aselimov** [derricw/siggo#20]
Hello! Currently whenever I try to send a message in siggo it gives me exit status 1 and I can't currently find very much information on what is going on. Are there any log files being written? I have linked my account using signal-cli and am able to send messages using signal-cli but the siggo sending doesn't work. I'm also able to see my contacts on siggo as well, just seems the message sending is broken for me. I'm on Artix linux and don't have systemd, not sure if that makes a difference. Thanks for the help!

**Comment by derricw** [comment]
Hey! Thanks for the report. Can you send messages manually using `signal-cli -u <+yournumber> send -m <+recipient_number> <message>`?

**Comment by aselimov** [comment]
Yes I can! It works sending to myself and other people

**Comment by derricw** [comment]
Hrmmm. I guess the next thing I'd look at is whether you can run `signal-cli` in daemon mode with:
`signal-cli -u <+phonenumber> daemon --json`

If that runs without error, the next thing I'd check is whether `signal-cli` is in your PATH, for `siggo` to find. If it is, then here is my recommendation:
1. Run `siggo` in debug mode using the `--debug` arg.
2. Look for errors in the logs which should be at `.local/share/siggo/siggo.log`, especially after sending a message.

**Comment by aselimov** [comment]
Oh yes, it seems to be a problem with the dbus. Haven't figured it out quite yet, but thanks for the help!
