### ISSUE TITLE
Message History not working

### ISSUE THREAD

**Issue by beune** [derricw/siggo#29]
```
$ siggo version
Build Date:
Git Commit:
Version: 0.8.1
Go Version: go1.15.6
OS/Arch: linux amd64
signal-cli Version: 0.7.2
```

I set `save_messages` to `true` in `config.yml`, but received messages do not persist when restarting `siggo`. However, the message files do show up in `~/.local/share/siggo/conversations`.

**Comment by derricw** [comment]
Hey @beune thanks for the report! I will try and take a look at this tomorrow.
