### ISSUE TITLE
Crashed when first opened

### ISSUE THREAD

**Issue by makeworld-the-better-one** [derricw/siggo#30]
A couple messages displayed after loading for the first time, then it crashed.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5591d4df4254]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc0002d8000)
	github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:244 +0x87
panic(0x5591d4feb900, 0x5591d524dc10)
	runtime/panic.go:969 +0x1b9
github.com/derricw/siggo/widgets.(*ContactListPanel).Render(0xc0001cce00)
	github.com/derricw/siggo/widgets/contactlist.go:73 +0x494
github.com/derricw/siggo/widgets.(*ChatWindow).update(0xc0002b8750)
	github.com/derricw/siggo/widgets/chatwindow.go:424 +0x69
github.com/derricw/siggo/widgets.NewChatWindow.func3.1()
	github.com/derricw/siggo/widgets/chatwindow.go:640 +0x2c
github.com/rivo/tview.(*Application).QueueUpdateDraw.func1()
	github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:716 +0x31
github.com/rivo/tview.(*Application).Run(0xc0002d8000, 0x0, 0x0)
	github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:371 +0x9a7
github.com/derricw/siggo/cmd.glob..func10(0x5591d5255180, 0x5591d52aac58, 0x0, 0x0)
	github.com/derricw/siggo/cmd/root.go:121 +0x45a
github.com/spf13/cobra.(*Command).execute(0x5591d5255180, 0xc0000121d0, 0x0, 0x0, 0x5591d5255180, 0xc0000121d0)
	github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x5591d5255180, 0x5591d4a4c625, 0xc000072058, 0x0)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
github.com/derricw/siggo/cmd.Execute()
	github.com/derricw/siggo/cmd/root.go:131 +0x2f
main.main()
	github.com/derricw/siggo/main.go:8 +0x25
```

May I suggest using [cview](https://gitlab.com/tslocum/cview/) instead of tview? I used it personally and it's great, and it has numerous improvements over the original.

**Comment by makeworld-the-better-one** [comment]
I set `save_messages` to `true` before opening it for the first time, could that be it? After setting it to false it no longer crashes.

**Comment by derricw** [comment]
Hey, thanks for the report! I will take a look at this.

**Comment by derricw** [comment]
After it ran successfully, did you turn message saving back on?

**Comment by makeworld-the-better-one** [comment]
I went to try and test this, but then it crashed again with the exact same stack trace. `save_messages` was `false` this time. I opened it, a message came in and was displayed, and then it crashed right away.

**Comment by derricw** [comment]
Hey @makeworld-the-better-one, sorry to hear. I'll take a look when I get a chance. I haven't tested it yet with signal-cli 0.7, and I fear that may be the cause of some of these issues. I have only ever used siggo with signal-cli 0.6.

Also, thanks so much for telling me about cview.

I started a new job in December and I haven't had as much time to hack on this project in the past 2 months, but I will try and look into this as soon as I can.

**Comment by makeworld-the-better-one** [comment]
Oh yeah, I'm using the latest signal-cli 0.7.4.

> Also, thanks so much for telling me about cview.

You're welcome, good luck with it! It's great.

And no worries. Thanks for getting back to me.

**Comment by kverb** [comment]
i've also been trying to get siggo running with 0.7.4. I have a patch that seems to work for me: https://gist.github.com/kverb/8541f95287dcd886f638406af36257b3

it seems there are two main issues that are affecting this and #29 : 
1. siggo is crashing on trying to load groups from signal-cli's data file. I believe this is caused by the `SignalGroup` structs' members type. Changing to a simple string list seems to fix it. 
2. siggo appears to be doing nothing when running. This is observable if you enable the log and see that it just continually loops on `starting dubs daemon... scanning stdout`. Perhaps this is due to a new warning that signal-cli emits upon launching in daemon mode : `WARN DaemonCommand - "--json" option has been deprecated, please use the global "--output=json" instead.` 

I'm not going to submit a PR, but please feel free to take a look at my patch changes.
